__author__ = 'Comma'

END = -1
MAIN_PANEL = 1

POST_START = 10
POST_SELECT_FIELD = 11
POST_FILL_VALUE = 12
POST_BEFORE_SUBMIT = 13
POST_SUBMIT = 14

UPDATE_START = 15
UPDATE_SELECT_TICKET = 16
UPDATE_SELECT_FIELD = 17
UPDATE_FILL_VALUE = 18
UPDATE_BEFORE_SUBMIT = 19
UPDATE_SUBMIT = 20

SEARCH_START = 21
SEARCH_SELECT_FIELD = 22
SEARCH_FILL_VALUE = 23
SEARCH_BEFORE_SUBMIT = 24
SEARCH_SUBMIT = 25

SUMMARY_LIST = 30
QUICK_SEARCH_MODE_SELECTION = 31
QUICK_SEARCH_LIST = 32
QUICK_SEARCH_SUBMIT = 33

TICKET_STAT_LIST = 34

SUPPORT_EVENT_START = 40
SUPPORT_EVENT_LIST = 41
